### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by shekhargahlot** [ICBI-SG/campus-workshop#1]
Getting the following error after executing npm install:
_The program 'npm' is currently not installed. To run 'npm' please ask your administrator to install the package 'npm'_

**Comment by Xenonym** [comment]
This seems to be an artifact of #2, maybe try logging into the VM, do `vim /vagrant/script.sh`, then `:set ff=unix`, save the file, log out and do `vagrant provision` and after it finishes npm should be installed!

**Comment by shekhargahlot** [comment]
Thanks. But still getting errors. vagrant provision is not working.
I tried different versions of script.sh but still unable to do so.

script.sh is giving Error1.txt.
script - Copy (2) [generated after following vim messages and removing /r and &&] is giving Error2.txt.

Please find attached the .txt of all the files (as I can't upload .sh in here).

[script - Copy (2).sh.txt](https://github.com/ICBI-SG/campus-workshop/files/786834/script.-.Copy.2.sh.txt)
[script.sh.txt](https://github.com/ICBI-SG/campus-workshop/files/786833/script.sh.txt)
[Error1.txt](https://github.com/ICBI-SG/campus-workshop/files/786829/Error1.txt)
[Error2.txt](https://github.com/ICBI-SG/campus-workshop/files/786830/Error2.txt)

**Comment by Xenonym** [comment]
Hmm, that updated script still seems to have DOS line endings. Try replacing the script.sh in your `campus-workshop` directory with the attached one, and try `vagrant provision` again:

[script.sh.txt](https://github.com/ICBI-SG/campus-workshop/files/786865/script.sh.txt)

**Comment by shekhargahlot** [comment]
Thanks. It worked.

**Comment by ernieteo** [comment]
Seems this issue comes up for certain groups and not for others. Would like to find out if there are some commonalities such as machine specs so that we can provide more concise instructions. Will find out more from you guys at the workshop.
