### ISSUE TITLE
script.sh has DOS line endings, will not run

### ISSUE THREAD

**Issue by Xenonym** [ICBI-SG/campus-workshop#2]
Hello,

`/vagrant/script.sh` seems to be accidentally saved with DOS line endings instead of Unix ones, this causes the provisioning to fail. 

Doing `:set ff=unix` on `vim`, resaving the script and doing `vagrant provision` after seems to fix it.

**Comment by ICBI-SG** [comment]
Hi, Thanks for your feedback. It should be working fine now, let us know if there are similar/other issues. :)
